from debian 
#cmd ["//bin/echo","$HOME"]
#entrypoint ["/bin/echo","$HOME"]
#entrypoint ["top","-b","-c"]
#entrypoint top -b -c
run echo "Foo Gee"
entrypoint ["top","-b"]
cmd ["-c"]
#cmd ["-b","-c"]

#cmd /bin/echo $HOME
#entrypoint ["ping"]
#cmd ["localhost"]
