from my/fedora_postgres
run dnf -y upgrade --setopt=deltarpm=false
run dnf -y install procps-ng
#entrypoint ["top"]
#cmd ["-b","-c"]
#cmd top -b -c
#cmd ["echo","$HOME"]
run echo 
run echo $HOME
run ["echo","$HOME"]
#run chmod o+rwx /
run ls -ld /
