from fedora
run ["echo","ϐ"]
run ["dnf","-y","upgrade","--refresh","--setopt=deltarpm=false"]
run ["dnf","-y","install","vim"]
run ["dnf","-y","install","procps-ng"]
run ["dnf","-y","install","net-tools"]
env LANG en_US.UTF-8
env TERM xterm-256color
#run ["dnf","-y","install","glibc-langpack-en"]
#env LC_ALL en_US.UTF-8

