from my/fedora-locale
run dnf -y upgrade --setopt=deltarpm=false
run echo "Π" >/1.txt
run useradd postgres
run echo "export LANG=en_US.utf8" >>/home/postgres/.bash_profile
run cat /home/postgres/.bash_profile 
run cat /1.txt
#entrypoint ["/script.sh"]
#cmd ["foo"]
